title: "Lisa Makes Stuff"
author: 
  name: "Lisa"
  email: "lisa.ribaudo@gmail.com"
description: "Data analysis and pretty things." # This will show up in places like twitter, linkedin, etc, if you share your sites url as a post.

# Email / Social media user names used by the minima theme:
# All of these are optional and can be removed or commented out
#email: "lisa.ribaudo@gmail.com"
#twitter_username: "twitteruser"
#github_username: "Gwren42"
#bluesky_username: "GrenW"
#linkedin_username: "linkedinuser"
#facebook_username: username
#flickr_username: username
#instagram_username: username
#pinterest_username: username
#youtube_username: username
#googleplus_username: +username

#########################################################################################
######### Nothing below needs to be changed (unless you know what you're doing) #########
#########################################################################################
# Build settings
remote_theme: jekyll/minima
